import localFont from "next/font/local";
import "./globals.css";
import NavChecker from "./components/NavChecker";
import { ContextProvider } from "./context/context";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
			>
				<ContextProvider>
					{/* Conditional Navigation */}
					<NavChecker />
					{/* Main Content */}
					{children}
				</ContextProvider>
			</body>
		</html>
	);
}
